// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sharp.Models;
using System;

namespace Sharp.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20180809111311_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sharp.Models.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Admin");

                    b.Property<bool>("BackOffice");

                    b.Property<bool>("Cashier");

                    b.Property<string>("ChildTag")
                        .HasMaxLength(50);

                    b.Property<string>("Css")
                        .HasMaxLength(50);

                    b.Property<string>("Icon")
                        .HasMaxLength(50);

                    b.Property<int>("LineNo");

                    b.Property<bool>("Live");

                    b.Property<bool>("Manager");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("RootTag")
                        .HasMaxLength(50);

                    b.Property<bool>("Supervisor");

                    b.Property<string>("Tag")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("Sharp.Models.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("DataBase")
                        .HasMaxLength(50);

                    b.Property<string>("MacAddress")
                        .HasMaxLength(100);

                    b.Property<int>("Port");

                    b.Property<string>("PostCode")
                        .HasMaxLength(10);

                    b.Property<string>("PublicIp")
                        .HasMaxLength(50);

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100);

                    b.Property<string>("StoreId")
                        .HasMaxLength(50);

                    b.Property<string>("StoreName")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("Tick");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Sharp.Models.UserStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20);

                    b.Property<string>("StoreId")
                        .HasMaxLength(50);

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.Property<string>("UserRole")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UserStores");
                });
#pragma warning restore 612, 618
        }
    }
}
